### ISSUE TITLE
Can't extract 'qt' package while setting up the environment

### ISSUE THREAD

**Issue by emma-oc** [joosthub/pytorch-nlp-tutorial-sf2017#1]
I followed the instructions to create conda environment, however when running `conda install jupyter` the process is stuck in
`Extracting packages ...
[qt                  ]|                                                                                                    |   0%` 
Not sure what's going on... Would really appreciate any help:)

**Comment by Yue-Duan** [comment]
Never mind... issue resolved automatically after trying a few times and waiting...

**Comment by emma-oc** [comment]
Never mind... issue resolved automatically after trying a few times and waiting...
