### ISSUE TITLE
Problem with conda install pytorch torchvision cuda80 -c soumith

### ISSUE THREAD

**Issue by beynac** [joosthub/pytorch-nlp-tutorial-sf2017#2]
Running: conda install pytorch torchvision cuda80 -c soumith after installing CUDA and getting: 

PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - cuda80 

Running: anaconda search -t conda cuda80 and getting: 

Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     maccallum_lab/meld-cuda80 |    0.4.5 | conda           | linux-64, osx-64
     maccallum_lab/openmm-cuda80 |    7.1.0 | conda           | linux-64, osx-64
     soumith/cuda80            |      1.0 | conda           | linux-64       
     soumith/magma-cuda80      |    2.1.0 | conda           | linux-64 

Can you please update instruction?

**Comment by rakesh-k** [comment]
Running into similar issue. Trying to install on windows.
```
PackageNotFoundError: Packages missing in current channels:

  - pytorch

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/soumith/win-64
  - https://conda.anaconda.org/soumith/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

```

**Comment by delip** [comment]
Hello, a lot of the setup is now simplified as we are moving to JupyterHub, but to answer your questions for people using this to setup from scratch, PyTorch does not support CUDA on OSX. (Most macbooks and macs don't come with cuda-compatible gpus anyways). To install without CUDA on OSX, use:

```
conda install pytorch torchvision -c soumith 
```
