### ISSUE TITLE
macOS 10.13.4 and Xcode 9.3 compatibility broken with CUDA Toolkit 9.1

### ISSUE THREAD

**Issue by iuribeferrari** [joosthub/pytorch-nlp-tutorial-sf2017#7]
While installing CUDNN I fell into this issue: 

https://devtalk.nvidia.com/default/topic/1032646/macos-10-13-4-and-xcode-9-3-compatibility-broken-with-cuda-toolkit-9-1/?offset=5#5254662

It appears that the after the last release of Xcode 9.3, the compatibility between Xcode and CUDA Toolkit 9.1 has been broken.

There doesn't seem to be any fix by Nvidia yet and the issue appears to be very recent. 

Has anybody else suffered the same? Did anybody find a way around this bug?

**Comment by iuribeferrari** [comment]
After asking for some help, we downgraded Xcode to version 8.3.3 and were able to walk around the issue. 

Nonetheless, the installation command for PyTorch "conda install pytorch torchvision cuda80 -c soumith" would not work and we had to install PyTorch from the git source.

**Comment by braingineer** [comment]
Hi @iuribeferrari 

Thanks for letting us know!  Are you a participant in our 2-day training?  If so, CUDA is not as big of a deal for getting things to run.  Also, O'Reilly hosts a jupyter hub during two days.  Finally, the NYC 2018 repo is [here](https://github.com/joosthub/pytorch-nlp-tutorial-ny2018) so please consider filing issues there for tutorial related matters. 

(edit, updated link, had pasted wrong one)
