### ISSUE TITLE
Pytorch 0.4 needed?

### ISSUE THREAD

**Issue by nigamv** [joosthub/pytorch-nlp-tutorial-sf2017#8]
Looks like quite a few improvements were added in pytorch 0.4. But installation is not easily available through conda. 
Is pytorch 0.4 needed or a lower version as 0.3.1.post2work ?

**Comment by nigamv** [comment]
Never mind this works 

## To install cuda 
conda install -c anaconda cudatoolkit 

## To install python 0.4 
conda install pytorch torchvision -c pytorch

**Comment by braingineer** [comment]
Hi @nigamv!

I writing this response assuming you are a participant in our upcoming 2-day training in NYC.  

We will not be using 0.4 this training session.  The teaching and learning goals are mostly agnostic to it, and  when you upgrade to 0.4, you will have to take note of a couple differences.  PyTorch folks are hosting a migration guide [here](http://pytorch.org/2018/04/22/0_4_0-migration-guide.html).  

For future issues, please file them here: https://github.com/joosthub/pytorch-nlp-tutorial-ny2018
